
#              /$$      /$$ /$$       /$$   /$$               /$$ /$$             /$$
#             | $$  /$ | $$| $$      |__/  | $$              | $$|__/            | $$
#    /$$   /$$| $$ /$$$| $$| $$$$$$$  /$$ /$$$$$$    /$$$$$$ | $$ /$$  /$$$$$$$ /$$$$$$
#   |  $$ /$$/| $$/$$ $$ $$| $$__  $$| $$|_  $$_/   /$$__  $$| $$| $$ /$$_____/|_  $$_/
#    \  $$$$/ | $$$$_  $$$$| $$  \ $$| $$  | $$    | $$$$$$$$| $$| $$|  $$$$$$   | $$
#     >$$  $$ | $$$/ \  $$$| $$  | $$| $$  | $$ /$$| $$_____/| $$| $$ \____  $$  | $$ /$$
#    /$$/\  $$| $$/   \  $$| $$  | $$| $$  |  $$$$/|  $$$$$$$| $$| $$ /$$$$$$$/  |  $$$$/
#   |__/  \__/|__/     \__/|__/  |__/|__/   \___/   \_______/|__/|__/|_______/    \___/  by Drygo

#        Github page: https://github.com/xDrygo/xWhitelist - X: https://x.com/eldrygo

# Welcome to the configuration file of the plugin xWhitelist.

# If is enabled the whitelist (true/false), it can be changed in-game with command /xwhitelist enable and /xwhitelist disable.
enabled: false

# MySQL database connection. You can modify the connection to the database here. (The database table that will be used is: whitelist)
database:
  enable: true
  type: mysql # mysql, mongodb
  credentials:
    host: "localhost"
    port: 3306
    database: "whitelist_database"
    username: "root"
    password: "password"
  mongodb_url: "mongodb://username:password@localhost:27017/database_name"

# NO DOT MODIFY
plugin:
  first_run: true