# Bienvenido a la configuraciÃ³n de XWhitelist. AquÃ­ puedes configurar la conexiÃ³n a la base de datos y los mensajes del plugin.

# ConfiguraciÃ³n de la base de datos MySQL
mysql:
  host: "localhost"
  port: 3306
  database: "whitelist_database"
  user: "root"
  password: "password"

# Mensajes del plugin
messages:
  player_not_whitelisted: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« No estÃ¡s en la whitelist."
  player_added: "&8[#ff0000&lX&r&lWhitelist&8] #a0ff72âœ” Se ha agregado al jugador %player% a la whitelist."
  player_removed: "&8[#ff0000&lX&r&lWhitelist&8] #ff7272âŒ El jugador %player% ha sido eliminado de la whitelist."
  whitelist_header: "&8[#ff0000&lX&r&lWhitelist&8] #fff18dğŸ“° Lista de jugadores en la whitelist:"
  whitelist_status: "&8[#ff0000&lX&r&lWhitelist&8] #fff18dğŸ“° Ahora la Whitelist esta %status%."
  whitelist_cleaned: "&8[#ff0000&lX&r&lWhitelist&8] #a0ff72âœ” La whitelist ha sido limpiada exitosamente."
  config_reloaded: "&8[#ff0000&lX&r&lWhitelist&8] #a0ff72âœ” ConfiguraciÃ³n recargada."
  error_already_whitelisted: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« El jugador %player% ya esta en la Whitelist."
  error_database: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« Error al conectar a la base de datos."
  error_player_argument_needed: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« Necesitas especificar un jugador."
  error_no_additional_arguments: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« No se necesitan argumentos en este comando."
  error_unknown_command: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« Comando desconocido. &7Usa &f/xwhitelist help &7para ver la lista de comandos."
  no_permission: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« No tienes permisos para ejecutar este comando."

# NO MODIFICAR
plugin:
  first_run: true