
#              /$$      /$$ /$$       /$$   /$$               /$$ /$$             /$$
#             | $$  /$ | $$| $$      |__/  | $$              | $$|__/            | $$
#    /$$   /$$| $$ /$$$| $$| $$$$$$$  /$$ /$$$$$$    /$$$$$$ | $$ /$$  /$$$$$$$ /$$$$$$
#   |  $$ /$$/| $$/$$ $$ $$| $$__  $$| $$|_  $$_/   /$$__  $$| $$| $$ /$$_____/|_  $$_/
#    \  $$$$/ | $$$$_  $$$$| $$  \ $$| $$  | $$    | $$$$$$$$| $$| $$|  $$$$$$   | $$
#     >$$  $$ | $$$/ \  $$$| $$  | $$| $$  | $$ /$$| $$_____/| $$| $$ \____  $$  | $$ /$$
#    /$$/\  $$| $$/   \  $$| $$  | $$| $$  |  $$$$/|  $$$$$$$| $$| $$ /$$$$$$$/  |  $$$$/
#    |__/  \__/|__/     \__/|__/  |__/|__/   \___/   \_______/|__/|__/|_______/    \___/  by Drygo

        #Github page: https://github.com/xDrygo/xWhitelist - X: https://x.com/eldrygo

# Welcome to the configuration file of the plugin XWhitelist.

# MySQL database connection. You can modify the connection to the database here.
mysql:
  host: "localhost"
  port: 3306
  database: "whitelist_database"
  user: "root"
  password: "password"

# Plugin messages. You can modify the messages of the plugin here.
messages:
  player_not_whitelisted: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« You are not in the whitelist."
  player_added: "&8[#ff0000&lX&r&lWhitelist&8] #a0ff72âœ” Added player %player% to the whitelist."
  player_removed: "&8[#ff0000&lX&r&lWhitelist&8] #ff7272âŒ Removed player %player% from the whitelist."
  whitelist_header: "&8[#ff0000&lX&r&lWhitelist&8] #fff18dğŸ“° List of player in the whitelist:"
  whitelist_cleaned: "&8[#ff0000&lX&r&lWhitelist&8] #a0ff72âœ” The whitelist has been cleared."
  config_reloaded: "&8[#ff0000&lX&r&lWhitelist&8] #a0ff72âœ” Plugin reloaded."
  already_whitelisted: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« The player %player% is already in the whitelist."
  player_argument_needed: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« You need to specify a player in the command."
  no_additional_arguments: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« No argument needed in this command."
  unknown_command: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« Unknown command. &7Use &f/xwhitelist help &7to see the command list."
  no_permission: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« You have no permission to use this command."
  error_database: "&8[#ff0000&lX&r&lWhitelist&8] #FF0000ğŸš« Database connection error."

# NO DOT MODIFY
plugin:
  first_run: true